BEU-Odev_1/Models/ErrorViewModel.cs
namespace BEU_Odev_1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BEU-Odev_1/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace BEU_Odev_1.Models
{
    public class Product
    {
        [Key]
        public int Id { get; set; }
        [Required]  
        public string Name { get; set; }    
        [Required]
        public string Description { get; set; } 
        public int Quantity { get; set; }   
        public double Price { get; set; }   
        public bool IsActive { get; set; }  
    }
}

BEU-Odev_1/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace BEU_Odev_1.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; } 
        [Required]  
        public string Name { get; set; }    
        [Required]
        public string Surname { get; set; }
        public string Email { get; set; }   
        public string Password { get; set; }
        [Required]
        public bool IsActive { get; set; }  

        public DateTime CreatedDate { get; set; }   
    }
}

BEU-Odev_1/Controllers/HomeController.cs
using BEU_Odev_1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BEU_Odev_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
       
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BEU-Odev_1/Controllers/ProductController.cs
using BEU_Odev_1.Data;
using BEU_Odev_1.Models;
using Microsoft.AspNetCore.Mvc;

namespace BEU_Odev_1.Controllers
{
    public class ProductController : Controller
    {

        private readonly ApplicationDbContext _db;
        public ProductController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IList<Product> ProductListesi = _db.Product.ToList();
            return View(ProductListesi);
        }
        public IActionResult Create()
        {

            return View();
        }

    
        [HttpPost]
        public IActionResult Create(Product o)
        {
            if (ModelState.IsValid)
            {
                _db.Add(o);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Error", "Home");
            }

        }
    }
}

BEU-Odev_1/Controllers/UserController.cs
using BEU_Odev_1.Data;
using BEU_Odev_1.Models;
using Microsoft.AspNetCore.Mvc;

namespace BEU_Odev_1.Controllers
{
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            
            IList<User> UserListesi = _db.User.ToList();
            return View(UserListesi);
        }
       
        public IActionResult Create()
        {

            return View();
        }

        fghkjfvfgfg
        [HttpPost]
        public IActionResult Create(User o)
        {
            if (ModelState.IsValid)
            {
                _db.Add(o);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Error", "Home");
            }

        }
    }
}

BEU-Odev_1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BEU-Odev_1/Views/Product/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

BEU-Odev_1/Views/Product/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

BEU-Odev_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BEU_Odev_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BEU_Odev_1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BEU_Odev_1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">Add User</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Create">Add Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BEU_Odev_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BEU-Odev_1/Views/User/Create.cshtml
@model User
<form method="post">
    <div class="mb-3">
        <label asp-for="Name"></label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
     <div class="mb-3">
        <label asp-for="Surname"></label>
        <input type="text" asp-for="Surname" class="form-control" />
    </div>
     <div class="mb-3">
        <label asp-for="Email"></label>
        <input type="email" asp-for="Email" class="form-control" />
    </div>
    <div class="mb-3">
        <label asp-for="Password"></label>
        <input type="password" asp-for="Password" class="form-control" />
    </div>
      <div class="mb-3">
        <label asp-for="IsActive"></label>
        <input type="checkbox" asp-for="IsActive" class="form-check-input" />
    </div>
    
          <div class="mb-3">
        <input type="submit" value="Save" class="btn btn-warning" asp-action="Create" />
        <a asp-controller="User" class="btn btn-info" asp-action="Index">Back to user list</a>
    </div>
</form>

BEU-Odev_1/Views/User/Index.cshtml
@model IList<User>
<h1>User List.</h1>
<table class="table">
    <tr><th>Id</th>
        <th>Surname</th>
        <th>Name</th>
        <th>Email</th>
        <th>Password</th>
        <th>Active</th>
        </tr>
@foreach(var item in Model){
<tr>
    <td>@item.Id</td>
    <td>@item.Name</td>
    <td>@item.Surname</td>
    <td>@item.Email</td>
    <td>@item.Password</td>
    <td>@item.IsActive</td>

</tr>
}
</table>
}